# Translations template for svs.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the svs project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
msgid ""
msgstr ""
"Project-Id-Version: svs 0.1.0\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-06-30 09:21+0300\n"
"PO-Revision-Date: 2016-06-30 09:34+0300\n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"X-Generator: Poedit 1.8.8\n"
"Last-Translator: Andrej Šliamin <Andrej.Sliamin@ku.lt>\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && "
"n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"
"Language: ru_RU\n"

#: src/svs/inacademia_server.py:194 src/svs/inacademia_server.py:211
#: src/svs/inacademia_server.py:247 src/svs/inacademia_server.py:260
#: src/svs/inacademia_server.py:273
msgid "Page not found."
msgstr "Страница не найдена."

#: src/svs/inacademia_server.py:344
msgid "Domain"
msgstr "Домен"

#: src/svs/inacademia_server.py:349
msgid "Country"
msgstr "Страна"

#: src/svs/inacademia_server.py:373
msgid "Affiliation"
msgstr "Принадлежность к организации"

#: src/svs/inacademia_server.py:373
msgid "Identifier"
msgstr "Идентификатор"

#: src/svs/inacademia_server.py:373
msgid "Authentication time"
msgstr "Время идентификации"

#: src/svs/inacademia_server.py:410 src/svs/oidc.py:92
msgid ""
"We could not complete your validation because an error occurred while "
"handling your request. Please return to the service which initiated the "
"validation request and try again."
msgstr ""
"Мы не смогли завершить вашу проверку, потому что произошла ошибка при "
"обработке вашего запроса. Пожалуйста, вернитесь на сервис, с которого "
"был инициирован запрос на проверку, и попробуйте ещё раз."

#: src/svs/oidc.py:154
msgid ""
"The authentication request could not be processed. Please return to the "
"service which initiated the validation request and try again."
msgstr ""
"Запрос идентификации не мог быть обработан. Пожалуйста, вернитесь на "
"сервис, с которого был инициирован запрос на проверку, и попробуйте ещё "
"раз."

#: src/svs/oidc.py:161
msgid "Configuration error for the service."
msgstr "Ошибка конфигурации сервиса."

#: src/svs/user_interaction.py:49
msgid "{client_name} requires the information below to be transferred:"
msgstr ""
"Пользователю {client_name} необходима ниже представленая информация:"

#: src/svs/templates/consent.mako:38
msgid "Consent - Your consent is required to continue."
msgstr "Согласие - Для продолжения необходимо ваше согласие."

#: src/svs/templates/consent.mako:61
msgid "Ok, accept"
msgstr "Хорошо, согласен"

#: src/svs/templates/consent.mako:66
msgid "No, cancel"
msgstr "Нет, отменить"

#: src/svs/templates/consent.mako:81 src/svs/templates/error.mako:68
msgid "Terms of service"
msgstr "Условия использования"

#: src/svs/templates/error.mako:26
msgid "Error - An error occurred."
msgstr "Ошибка - Произошла ошибка."

#: src/svs/templates/error.mako:44
msgid "message"
msgstr "сообщение"

#: src/svs/templates/error.mako:53
msgid "Timestamp"
msgstr "Временная отметка"

#: src/svs/templates/error.mako:58
msgid "Error id"
msgstr "Идентификатор ошибки"
